primitiv/primitiv

examples/encdec/encdec.py
examples/mnist/mnist_multi_gpu.py
examples/xor/xor.py

Fix next bugs in example code 
1. some semicolon at end of sentence
2. one variable scope

Fix some small bugs in example sources

---

README.md

add installation guide of protobuf for Ubuntu

---

primitiv/trainer.cc
primitiv/trainer_impl.cc
primitiv/trainer_impl.h
test/trainer_impl_test.cc

Add [AdaGrad](http://jmlr.org/papers/v12/duchi11a.html) optimizer.

AdaGrad optimizer

---

primitiv/trainer.cc
primitiv/trainer_impl.cc
primitiv/trainer_impl.h
test/trainer_impl_test.cc

Add [RMSProp](https://www.cs.toronto.edu/~tijmen/csc321/slides/lecture_slides_lec6.pdf) optimizer for #7

RMSProp Optimizer

---

primitiv/trainer.cc
primitiv/trainer_impl.cc
primitiv/trainer_impl.h
python-primitiv/primitiv/_trainer.pyx
python-primitiv/primitiv/trainers/__init__.py
python-primitiv/primitiv/trainers/_trainer_impl.pxd
python-primitiv/primitiv/trainers/_trainer_impl.pyx
python-primitiv/tests/trainer_virtuals.py
test/trainer_impl_test.cc

Add RMSProp Optimizer in Python for #7

RMSProp Optimizer in Python

---

examples/encdec/encdec.cc
examples/encdec/encdec.py
examples/encdec/encdec_attention.cc
examples/encdec/encdec_attention.py
examples/mnist/mnist.cc
examples/mnist/mnist.py
examples/mnist/mnist_multi_gpu.cc
examples/mnist/mnist_multi_gpu.py
examples/ptb/ptb_rnnlm.cc
examples/ptb/ptb_rnnlm.py
examples/ptb/ptb_rnnlm_lstm.cc
examples/ptb/ptb_rnnlm_lstm.py
examples/ptb/ptb_rnnlm_sru.cc
examples/ptb/ptb_rnnlm_sru.py
examples/xor/xor.cc
examples/xor/xor.py
primitiv/graph.h
primitiv/tensor.cc
primitiv/tensor.h
python-primitiv/primitiv/_graph.pxd
python-primitiv/primitiv/_graph.pyx
python-primitiv/primitiv/_tensor.pxd
python-primitiv/primitiv/_tensor.pyx
test/graph_test.cc
test/tensor_test.cc

This PR adds below functions:
* `Node::backward()`: wrapper of `Graph::backward(Node)`.
* `Tensor::to_float()`: wrapper of `Tensor::to_vector()[0]` with shape checking.
* `Node::to_float()`: wrapper of `Node::to_vector()[0]`with shape checking.

Add Node::backward(), Tensor/Node::to_float.

---

python-primitiv/primitiv/_graph.pyx
python-primitiv/primitiv/_tensor.pyx

* Add type identifier of an argument in `Tensor.__init__()`.
* Fix condition inversion in `Node.__init__()`.

Fix initializer of Tensor and Node.

---

python-primitiv/primitiv/_device.pxd
python-primitiv/primitiv/_device.pyx
python-primitiv/primitiv/_graph.pxd
python-primitiv/primitiv/_graph.pyx
python-primitiv/primitiv/_initializer.pxd
python-primitiv/primitiv/_parameter.pxd
python-primitiv/primitiv/_shape.pxd
python-primitiv/primitiv/_tensor.pxd
python-primitiv/primitiv/_trainer.pxd
python-primitiv/primitiv/_trainer.pyx
python-primitiv/primitiv/devices/_cuda_device.pxd
python-primitiv/primitiv/devices/_cuda_device.pyx
python-primitiv/primitiv/devices/_naive_device.pxd
python-primitiv/primitiv/devices/_naive_device.pyx
python-primitiv/primitiv/initializers/_initializer_impl.pxd
python-primitiv/primitiv/tensor_op.h
python-primitiv/primitiv/trainers/_trainer_impl.pxd

This PR includes:
- Removing redundant namespace specifications.
- Removing duplicated pointer members in Device and Graph.
- Some small fixes.

Some refactoring in Python implementations.

---

python-primitiv/primitiv/_parameter.pyx

Small bug fix

---

.travis.yml

This branch adds Debian and Fedora settings for Travis CI.

Add debian and fedora build settings

---

.travis.yml
.travis/debian.sh
.travis/fedora.sh
.travis/osx.sh
.travis/ubuntu.sh

This branch adds a build script for OSX on Travis CI, and separate scripts into multiple files.

Add osx build and separate scripts into each OS

---

.travis/debian.sh

Fix travis script for Debian

---

examples/mnist/mnist_multi_gpu.cc
primitiv/CMakeLists.txt
primitiv/model.cc
primitiv/model.h
primitiv/parameter.cc
primitiv/parameter.h
primitiv/trainer.cc
test/model_test.cc

Related to: #30.
This PR adds `save` and `load` functions to `Model` class.

Add Model::save() and load()

---

examples/encdec/encdec.py
examples/encdec/encdec_attention.cc
examples/encdec/encdec_attention.py
examples/encdec/lstm.py
python-primitiv/primitiv/_optimizer.pxd
python-primitiv/primitiv/_optimizer.pyx

And adding a missing function `Model.add_model()`.

Update encoder-decoder example.

---

.travis/debian.sh
.travis/fedora.sh
.travis/ubuntu.sh
test/tensor_backward_test.cc
test/tensor_ops_test.cc
test/tensor_test.cc

and skip some tensor tests when no device is installed.

Add OpenCL tests for linux on travis

---

primitiv/functions.h
primitiv/node_funcs.cc
primitiv/operator_impl.cc
primitiv/operator_impl.h
primitiv/tensor_funcs.cc
test/operator_impl_test.cc
test/tensor_forward_test.cc

Add `functions::stop_gradient()` function:
- Forward: `y = x`
- Backward: `dy/dx = 0`

Add stop-gradient function.

---

primitiv/device.cc
primitiv/graph.cc
primitiv/graph.h
primitiv/parameter.h
primitiv/shape_ops.cc
primitiv/shape_ops.h
primitiv/tensor.h
test/shape_ops_test.cc

This modification reduces implicit dependencies between sub-module in the library.

Chagnge Class::shape() functions to return a new Shape object.

---

test/cuda_memory_pool_test.cc

Incorrect comparison between signed and unsigned int was fixed.

fix a small bug on test

---

primitiv/cuda_device.cu
primitiv/device.h
primitiv/naive_device.cc
primitiv/opencl_device.cc
primitiv/tensor.cc
primitiv/tensor.h
test/tensor_backward_test.cc
test/tensor_forward_test.cc
test/tensor_test.cc

This PR removes all public accessors to inner handles in the Tensor objects.

Remove Tensor::data() functions.

---

CMakeLists.txt

Fix version number in CMakeLists.

Pre-release v0.3.1
